steamword = [{text: "Dead by Daylight", size: 100},
{text: "Counter-Strike 2", size: 99},
{text: "Left 4 Dead 2", size: 81},
{text: "Apex Legends", size: 75},
{text: "Among Us", size: 73},
{text: "Phasmophobia", size: 73},
{text: "ARK: Survival Of The Fittest", size: 67},
{text: "ARK: Survival Evolved", size: 65},
{text: "The Forest", size: 64},
{text: "Wallpaper Engine", size: 63},
{text: "PUBG: BATTLEGROUNDS", size: 59},
{text: "Destiny 2", size: 58},
{text: "PAYDAY 2", size: 56},
{text: "Garry's Mod", size: 53},
{text: "Grand Theft Auto V", size: 53},
{text: "Brawlhalla", size: 52},
{text: "Warframe", size: 52},
{text: "Little Nightmares", size: 50},
{text: "Team Fortress 2", size: 49},
{text: "VRChat", size: 49},
{text: "Don't Starve Together", size: 48},
{text: "Portal 2", size: 47},
{text: "Deceit", size: 45},
{text: "Terraria", size: 45},
{text: "Unturned", size: 45},
{text: "Tom Clancy's Rainbow Six Siege - Test Server", size: 44},
{text: "Tom Clancy's Rainbow Six Siege", size: 44},
{text: "Paladins - Public Test", size: 44},
{text: "Black Desert", size: 44},
{text: "Paladins", size: 44},
{text: "The Sims™ 4", size: 42},
{text: "Fall Guys", size: 41},
{text: "Tomb Raider", size: 40},
{text: "Borderlands 2", size: 39},
{text: "Aimlabs", size: 39},
{text: "MultiVersus", size: 39},
{text: "7 Days to Die", size: 39},
{text: "Call of Duty®", size: 39},
{text: "Lethal Company", size: 39},
{text: "Lost Ark", size: 38},
{text: "Rust", size: 38},
{text: "Rust - Staging Branch", size: 38},
{text: "Stardew Valley", size: 37},
{text: "Crab Game", size: 36},
{text: "SMITE", size: 36},
{text: "SMITE - Public Test", size: 36},
{text: "Halo Infinite", size: 35},
{text: "Left 4 Dead", size: 34},
{text: "Dota 2", size: 34},
{text: "Outlast", size: 33},
{text: "The Witcher 3: Wild Hunt", size: 33},
{text: "Dying Light", size: 32},
{text: "DEVOUR", size: 32},
{text: "Raft", size: 31},
{text: "Life is Strange™", size: 30},
{text: "Portal", size: 30},
{text: "Friday the 13th: The Game", size: 30},
{text: "THE FINALS", size: 28},
{text: "ELDEN RING", size: 27},
{text: "Path of Exile", size: 27},
{text: "Valheim", size: 27},
{text: "Company of Heroes 2", size: 26},
{text: "Vampire: The Masquerade - Bloodhunt", size: 26},
{text: "UNO", size: 26},
{text: "Call of Duty: Black Ops III", size: 25},
{text: "War Thunder", size: 25},
{text: "Warhammer: Vermintide 2", size: 25},
{text: "For Honor", size: 25},
{text: "For Honor - Public Test", size: 25},
{text: "Hunt: Showdown (Test Server)", size: 24},
{text: "Rocket League", size: 24},
{text: "The Elder Scrolls V: Skyrim Special Edition", size: 24},
{text: "H1Z1: Test Server", size: 24},
{text: "Hunt: Showdown", size: 24},
{text: "SCP: Secret Laboratory", size: 24},
{text: "Z1 Battle Royale", size: 24},
{text: "New World", size: 23},
{text: "Project Zomboid", size: 23},
{text: "Sons Of The Forest", size: 23},
{text: "Bloons TD 6", size: 23},
{text: "Resident Evil 2", size: 23},
{text: "Human Fall Flat", size: 22},
{text: "Killing Floor", size: 22},
{text: "Splitgate", size: 22},
{text: "Fallout 4", size: 22},
{text: "Killing Floor Mod: Defence Alliance 2", size: 22},
{text: "Minion Masters", size: 22},
{text: "No More Room in Hell", size: 22},
{text: "Castle Crashers", size: 21},
{text: "Outlast 2", size: 21},
{text: "Pacify", size: 21},
{text: "Deathgarden: BLOODHARVEST", size: 20},
{text: "Tell Me Why", size: 20},
{text: "Half-Life", size: 20},
{text: "Half-Life 2: Lost Coast", size: 20},
{text: "Stick Fight: The Game", size: 20},
{text: "Doki Doki Literature Club", size: 20},
{text: "Golf With Your Friends", size: 20},
{text: "Half-Life 2", size: 20},
{text: "Metro 2033", size: 20}
];
